server:
  port: 8888


spring:

  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
#        native:
#            search-locations: file:///Users/uicheon/IdeaProjects/spring-stduy/spring-cloud-gateway/native-file-repo
        git:
          uri: https://github.com/KYankee6/spring-cloud-config
encrypt:
#  key: myNameIsJoonHyeokYangSpaceIotIsRocking
  key-store:
#    location: file://${user.home}/IdeaProjects/spring-stduy/spring-cloud-gateway/keystore/apiEncryptionKey.jks
    location: file:/apiEncryptionKey.jks
    password: test1234
    alias: apiEncryptionKey
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httpExchange, busrefresh